@startuml
'https://plantuml.com/class-diagram

+class Ship{
#shipName:String
#yearBuilt:String
+yearBuilt():String
+getShipName():String
+setShipName(String shipName):void
+setYearBuilt(String yearBuilt):void
+toString():String
}

+class CruiseShip{
#passengers:int
+getPassengers():int
+setPassengers(int passengers):void
+toString():String
}

+class CargoShip{
#cargoTonnage:int
+getCargoTonnage():int
+setCargo_tonnage(int cargoTonnage):void
+toString():String
}
Ship <|-- CargoShip
Ship <|-- CruiseShip

@enduml